name: Auto Update Game

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Godot
        uses: firebelley/godot-ci@v4.1.0
        with:
          version: 4.0
          
      - name: Export Game
        run: godot --export-release "Windows Desktop" build/game.exe

      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: game-build
          path: build/
